import {
  promptForAssetPlan,
  promptForResearch,
  promptForScript,
  promptForStoryboard,
  promptForVoiceMusic,
  validateAssetPlan,
  validateResearch,
  validateScript,
  validateStoryboard,
  validateVoiceMusicPlan,
  type ProductionPackage,
} from "./production-content.js";
import { generationProviderStatus } from "./generation-provider.js";

export const PRODUCTION_ORCHESTRATION_STAGES = ["research", "script", "storyboard", "assets", "voice_music"] as const;

export type ProductionOrchestrationStage = typeof PRODUCTION_ORCHESTRATION_STAGES[number];

export type ProductionOrchestrationStep =
  | { kind: "generate"; stage: ProductionOrchestrationStage }
  | { kind: "awaiting_approval"; stage: ProductionOrchestrationStage }
  | { kind: "blocked"; stage: ProductionOrchestrationStage; reason: string }
  | { kind: "awaiting_quality_review"; checks: string[] }
  | { kind: "awaiting_final_approval" }
  | { kind: "production_ready" };

export interface ProductionStagePlan {
  stage: ProductionOrchestrationStage;
  activeState: string;
  readyState: string;
  agentKeys: string[];
  prompt: string;
  validate(value: unknown): unknown;
  commit(packageData: ProductionPackage, output: unknown): void;
}

const STAGE_PREREQUISITES: Partial<Record<ProductionOrchestrationStage, ProductionOrchestrationStage>> = {
  script: "research",
  storyboard: "script",
  assets: "storyboard",
  voice_music: "assets",
};

export function nextProductionOrchestrationStep(packageData: ProductionPackage): ProductionOrchestrationStep {
  for (const stage of PRODUCTION_ORCHESTRATION_STAGES) {
    const status = packageData.stageStatuses[stage];
    if (status === "generated") {
      if (packageData.approvalState[stage]?.status !== "approved") return { kind: "awaiting_approval", stage };
      continue;
    }

    const prerequisite = STAGE_PREREQUISITES[stage];
    if (prerequisite && (packageData.stageStatuses[prerequisite] !== "generated" || packageData.approvalState[prerequisite]?.status !== "approved")) {
      return { kind: "blocked", stage, reason: `Approve '${prerequisite}' before generating '${stage}'.` };
    }
    return { kind: "generate", stage };
  }

  const requiredChecks = ["educationalQuality", "ageSuitability", "factualReview", "copyrightSourceReview"] as const;
  const outstandingChecks = requiredChecks.filter((check) => packageData.qualityChecks[check] !== "human_approved");
  if (outstandingChecks.length > 0) return { kind: "awaiting_quality_review", checks: [...outstandingChecks] };
  if (packageData.qualityChecks.humanApproval !== "approved") return { kind: "awaiting_final_approval" };
  return { kind: "production_ready" };
}

export function createProductionStagePlan(packageData: ProductionPackage, stage: ProductionOrchestrationStage): ProductionStagePlan {
  const feedback = packageData.approvalState[stage]?.feedback;
  switch (stage) {
    case "research":
      return {
        stage,
        activeState: "research_ready",
        readyState: "curriculum_ready",
        agentKeys: ["librarian", "explorer"],
        prompt: promptForResearch(packageData.brief),
        validate: validateResearch,
        commit: (result, value) => {
          const output = value as ReturnType<typeof validateResearch>;
          result.learningOutcomes = output.learningOutcomes;
          result.researchNotes = { status: "generated", notes: output.researchNotes, sources: [], verification: "unverified" };
          result.stageStatuses.research = "generated";
          result.approvalState.research = { status: "pending" };
        },
      };
    case "script":
      return {
        stage,
        activeState: "script_ready",
        readyState: "script_ready",
        agentKeys: ["planner", "writer"],
        prompt: promptForScript(packageData.brief, packageData.researchNotes.notes, packageData.learningOutcomes) + (feedback ? `\nRevision feedback: ${feedback}` : ""),
        validate: validateScript,
        commit: (result, value) => {
          const output = value as ReturnType<typeof validateScript>;
          result.script = { status: "generated", content: output };
          result.episodeTitle = output.title;
          result.title = output.title;
          result.stageStatuses.script = "generated";
          result.approvalState.script = { status: "pending" };
          result.deliverables.script.status = `Generated by ${generationProviderStatus().provider}; review pending`;
        },
      };
    case "storyboard":
      if (!packageData.script.content) throw new Error("The approved script content is unavailable.");
      return {
        stage,
        activeState: "storyboard_ready",
        readyState: "storyboard_ready",
        agentKeys: ["visualizer"],
        prompt: promptForStoryboard(packageData.brief, packageData.script.content) + (feedback ? `\nRevision feedback: ${feedback}` : ""),
        validate: (value) => {
          const scenes = validateStoryboard(value);
          const scriptIds = packageData.script.content!.scenes.map((scene) => scene.id);
          if (scenes.length !== scriptIds.length || scenes.some((scene, index) => scene.id !== scriptIds[index])) {
            throw new Error("Invalid structured output: storyboard scene ids must match the source script in order");
          }
          return scenes;
        },
        commit: (result, value) => {
          const output = value as ReturnType<typeof validateStoryboard>;
          result.scenes = output;
          result.storyboardBeats = output;
          result.stageStatuses.storyboard = "generated";
          result.approvalState.storyboard = { status: "pending" };
          result.deliverables.storyboard.status = `Specification generated by ${generationProviderStatus().provider}; review pending`;
        },
      };
    case "assets":
      return {
        stage,
        activeState: "animation_ready",
        readyState: "animation_ready",
        agentKeys: ["experimenter"],
        prompt: promptForAssetPlan(packageData.brief, packageData.scenes) + (feedback ? `\nRevision feedback: ${feedback}` : ""),
        validate: validateAssetPlan,
        commit: (result, value) => {
          const output = value as ReturnType<typeof validateAssetPlan>;
          result.characters = output.characters;
          result.visualAssets = output.visualAssets;
          result.stageStatuses.assets = "generated";
          result.approvalState.assets = { status: "pending" };
        },
      };
    case "voice_music":
      if (!packageData.script.content) throw new Error("The approved script content is unavailable.");
      return {
        stage,
        activeState: "audio_ready",
        readyState: "audio_ready",
        agentKeys: ["podcaster"],
        prompt: promptForVoiceMusic(packageData.brief, packageData.script.content) + (feedback ? `\nRevision feedback: ${feedback}` : ""),
        validate: validateVoiceMusicPlan,
        commit: (result, value) => {
          const output = value as ReturnType<typeof validateVoiceMusicPlan>;
          result.voicePlan = output;
          result.musicSfxPlan = output;
          result.stageStatuses.voice_music = "generated";
          result.approvalState.voice_music = { status: "pending" };
          result.deliverables.audio.status = `Plan generated by ${generationProviderStatus().provider}; audio not rendered`;
        },
      };
  }
}